# Generated by Django 4.1 on 2022-09-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210310_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMSData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('work', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'PMS Analytics Data',
            },
        ),
        migrations.DeleteModel(
            name='CountryData',
        ),
    ]
